version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      OPS: "MrBoomPL"
      MOTD: "Welcome to TESTHUB Craft"
      SPAWN_PROTECTION: 0
    restart: unless-stopped
    volumes:
      - ./data:/data

